### ISSUE TITLE
Iteration with index: forElement

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#219]
I remember that this came up a couple of days ago and I think I better put an issue here, so we don't forgot it.

Essentially the idea is to iterate over every element but also provide an index to the user.

Name suggestion: `forElement`, `byElementIndex`
##

**Comment by dextorious** [comment]
Perhaps I can supply a bit of context here, as I also ran into this yesterday. Essentially, it's syntactically convenient to write some algorithms roughly like this:

```
for(auto elems = slice.byElement; !elems.empty; elems.popFront)
{
    i = elems.index[0];
    j = elems.index[1];
    // some operations on arbitrary elements that depend on indices
}
```

However, since only the slice.byElement range itself has access to the current indices, one cannot easily use this pattern on `foreach` loops. As a trivial example, it may be convenient to write something like

```
foreach(elem; taskPool.parallel(slice.byElementIndex)) 
{
    i = elem.index[0];
    j = elem.index[1];
    // index-dependent operations
}
```

Currently, this requires uglier solutions like nested loops to conserve knowledge of the structure of the slice. For generality, it might also be desirable to be able to control the pattern of iteration, but that's a secondary concern.

**Comment by 9il** [comment]
blocked by language
