### ISSUE TITLE
convenience method to get the original array

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#232]
@9il I saw that people are fighting with the conversion from slices to ndslice and often result to `byElement.array`. How about making this more convenient and _faster_ by giving them easy access to original dynamic array?

Could be something simple like:

``` d
static if (isDynamicArray!Range && replaceArrayWithPointer)
{
    ElementType!(Range)[] array() const
    {
        return slice.ptr[0.. slice.elementsCount];
    }
}
```
##

**Comment by 9il** [comment]
This is not simple. For `Slice!(T*, N)` it is just impossible for common case

**Comment by 9il** [comment]
`ptr` may refer to not the first element (in memory)

**Comment by wilzbach** [comment]
> This is not simple. 

Sorry about the wrong wording :disappointed: 

> For Slice!(T*, N) it is just impossible for common case
> `ptr` may refer to not the first element 

Yes, but if the input source was a [Dynamic array](https://dlang.org/spec/arrays.html#dynamic-arrays), we should be able to get it back?

**Comment by 9il** [comment]
we are not able in common case

**Comment by wilzbach** [comment]
> we are not able in common case

hence the `static if` ;-)

**Comment by 9il** [comment]
> we are not able in common case
> hence the static if ;-)

does not matter. Is has pointer to the first element, strides and length. It may not be consequent and continues in memory

**Comment by PetarKirov** [comment]
I also hit that problem. The solution, IMO, is to add a function (e.g. isFlatArray or isContiguousInMemory) that checks the lengths and strides and returns true if it is safe to do `slice.ptr[0 .. elementCount]`. We can either add a function (e.g. `getRawSlice` or `array`) that checks the above and throws a RangeError in case !isFlatArray and otherwise returns the slice of all elements, or we can just leave this to the user which is possibly un-`@safe`.

For me, something like isContiguousInMemory is really a must have, because it answers the question: Can I use `memcpy` and friends?, which is definitely a huge performance win.

On a related topic, what do you think about a bifacial version of `Slice`, where the lenghts and strides are known at CT? This is certainly a niche case, but not that uncommon for some applications where the data size, or at least the chunk sizes are known ahead of time / by definition. For example in computer graphics lengths and strides of 2D, 3D and 4D vectors (`Slice!(float, 1)`) and matrices (`Slice!(float, 2)`) are quite fixed. All versions of functions that operate on such Slices and take runtime parameters (e.g. `slice.swapped(2, 3)`, instead of `slice.swapped!(2, 3)`) would return normal Slices (i.e. with runtime lengths and strides).
The benefits is quite clear (at least for me) - no need to store the lengths and strides, the elements can be stored in place (which is definitely more optimal for small vectors and matrices), many range transformations can be performed at compile-time, `getRawSlice` can be guarded by `static if`, instead of a runtime check, etc, etc.

**Comment by rljubobratovic** [comment]
Hey guys,

> For me, something like isContiguousInMemory is really a must have

+1 on this one. In computer vision tasks I use slice to represent images. Access to raw pointer to array and query if contained memory is contiguous was much needed feature in various occasions.

**Comment by 9il** [comment]
> On a related topic, what do you think about a bifacial version of Slice, where the lenghts and strides are known at CT? This is certainly a niche case, but not that uncommon for some applications where the data size, or at least the chunk sizes are known ahead of time / by definition. For example in computer graphics lengths and strides of 2D, 3D and 4D vectors (Slice!(float, 1)) and matrices (Slice!(float, 2)) are quite fixed. All versions of functions that operate on such Slices and take runtime parameters (e.g. slice.swapped(2, 3), instead of slice.swapped!(2, 3)) would return normal Slices (i.e. with runtime lengths and strides).
> The benefits is quite clear (at least for me) - no need to store the lengths and strides, the elements can be stored in place (which is definitely more optimal for small vectors and matrices), many range transformations can be performed at compile-time, getRawSlice can be guarded by static if, instead of a runtime check, etc, etc.

This should be separate package, not `ndslice` because it has completely different implementation.

**Comment by 9il** [comment]
> Hey guys,
> 
> For me, something like isContiguousInMemory is really a must have
> +1 on this one. In computer vision tasks I use slice to represent images. Access to raw pointer to array and query if contained memory is contiguous was much needed feature in various occasions.

Phobos PRs are welcome ) `ndslice` would be removed from `mir` as soon as LDC get DMD FE 2.072.

**Comment by PetarKirov** [comment]
Alright, I l'll give it a shot :P

**Comment by PetarKirov** [comment]
About the CT-known lenghts and strides version of ndslice - yeah the implementation would be different, but I hope that much of the range / ndslice operators could be reused. Anyhow, I should probably open another issue to discuss this, and there may be unforseen problems, so PR-centered discussion would be best I guess.

I'll start working on a Phobos PR for isContiguousInMemory for now.

**Comment by PetarKirov** [comment]
Hi @9il! I didn't have much time lately, but I think I've managed to implement `isContiguousInMemory`. I'm not sure if it's right approach, because I think it may have some overlap with the work you've been doing on `ndslice.algorithm`.
Can you take a look at my solution and let me know if it's the right approach? If that's the case, I'll submit a Phobos PR. Here's my WIP commit: https://github.com/dlang/phobos/compare/master...ZombineDev:ndslice-contiguous-layout
I still need to write proper documentation, but I think you should get the idea from the unittest.

**Comment by 9il** [comment]
@ZombineDev There more elegant implementation: construct iotaSlice with the same shape and return true if it has the same strides as the original array. Also I prefer to use `goto` instead of `&&`. This is easy to optimise for compiler. Also, `isContinuous` should be split from CT check, that underlaying range is memory.

**Comment by PetarKirov** [comment]
> There more elegant implementation: construct iotaSlice with the same shape and return true if it has the same strides as the original array. Also I prefer to use goto instead of &&. This is easy to optimise for compiler.

I did that because I was worried about the codegen. From the various things I tried, that yielded the fastest code with LDC. Here's the assembly for N=12: [isContiguousInMemory disasm](https://gist.github.com/anonymous/62385352a74db59e9fde65ce5855f9ef) and [full program disasm](http://tinyurl.com/gp5nmuz).
  Let me know if you want me to try to implement it using goto. 

> Also, isContinuous should be split from CT check, that underlaying range is memory.

I did that at first, but at the same time I wanted to have as much information at compile-time, so I ended providing the ability to test if a slice in not contiguous at compile-time - see the `static assert` in the unittest.

**Comment by PetarKirov** [comment]
BTW I'm not sure about the name. If you have a better suggestion than `isContiguousInMemory`, I'll be happy to change the name. I used the word "contiguous" because it implies "continuous" and is commonly used term in that area. See also the [Contiguous Iterators: A Refinement of Random Access Iterators](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3884.pdf) C++ proposal.

**Comment by 9il** [comment]
name: `isContiguous` (without check that it is memory)
module:`ndslice.slice`
code: 

``` d
foreach(...) // static
{
    if(...)
        goto False;
}
return true;
False: return false;
```

this will reduce machine code size.

Please add `Postcondition` to `sliced` and `slice` that returned slice is contiguous.

**Comment by PetarKirov** [comment]
## 1. Performance

l tried couple of things and I got mixed results between DMD and LDC. [There](https://dpaste.dzfl.pl/8cc751aebbf1)'s my benchmark code and here are the results. The first is DPaste (for which I had to limit the number of iterations) and the other two I performed locally on my Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz Linux 4.5.0 x86_64 machine with `LDC 1.1.0-alpha1` and DMD nightly (dmd-2016-06-23).
- DPaste (with DMD 2.071.1 -m64, no optimizations):
  Benchmarking with 230000 iterations. Results:
  checkslice_1 took 216.541ms
  checkslice_2 took 201.674ms
  checkslice_3 took 202.950ms
  checkslice_4 took 202.478ms
  checkslice_5 took 201.880ms
- `dmd -O -release -inline slice_structure_asm_check.d && ./slice_structure_asm_check`:
  Benchmarking with 230000 iterations. Results:
  checkslice_1 took 90.711ms
  checkslice_2 took 104.657ms
  checkslice_3 took 107.040ms
  checkslice_4 took 104.590ms
  checkslice_5 took 104.626ms
  
  Benchmarking with 10000000 iterations. Results:
  checkslice_1 took 3971.553ms
  checkslice_2 took 4557.489ms
  checkslice_3 took 4559.947ms
  checkslice_4 took 4550.599ms
  checkslice_5 took 4547.693ms
- `../../ldc2-1.1.0-alpha1-linux-x86_64/bin/ldc2 -O5 -release slice_structure_asm_check.d && ./slice_structure_asm_check`:
  Benchmarking with 230000 iterations. Results:
  checkslice_1 took 127.306ms
  checkslice_2 took 1.152ms
  checkslice_3 took 1.227ms
  checkslice_4 took 1.227ms
  checkslice_5 took 1.152ms
  
  Benchmarking with 10000000 iterations. Results:
  checkslice_1 took 3913.239ms
  checkslice_2 took 42.960ms
  checkslice_3 took 45.777ms
  checkslice_4 took 45.804ms
  checkslice_5 took 43.253ms
  
  Benchmarking with 100000000 iterations. Results:
  checkslice_1 took 38622.844ms
  checkslice_2 took 429.623ms
  checkslice_3 took 458.151ms
  checkslice_4 took 457.402ms
  checkslice_5 took 430.411ms

Overall with DMD, there's little to no difference between: 2) using a boolean expression generated with mixin 3) boolean expression constructed with static foreach 4) static foreach + goto 5) static foreach + early return. What surprised me the most was that the version 1)  with runtime foreach was consistently faster on my machine, in contrast with the DPaste and LDC results (and common sense).

From my interpretation of the LDC results, the 2), 3), 4) and 5) implementations have roughly performance, but the mixin-ed boolean expression - 2) - and the early return version - 5) - had the edge.

# 

About the codesize, I've uploaded the interesting parts of the output of `ldc2-1.1.0-alpha1-linux-x86_64/bin/ldc2 -O5 -release slice_structure_asm_check.d -output-s` [here](https://gist.github.com/ZombineDev/75e9caba6f205b566ad3cbfae6496032).
- checkslice_1 -> 161 lines
- checkslice_2 -> 97 lines
- checkslice_3 -> 97 lines
- checkslice_4 -> 68 lines
- checkslice_5 -> 67 lines

# 

Considering that 5) is the most readable (at least IMO), and that it yields faster and smaller code (both in source and object form) than the alternatives, I'll go ahead with it.

## 2. Naming

I prefer the `isContiguous` name too. But I wonder if I should refactor the `is(PureRange == Range) && hasPtrBehavior!PureRange` check into an `enum isMemory`. That way `isContiguous` would useable for Slices such as Iota and if the users want they can use `isMemory && isContiguous` to see if they can use `memcpy`.

BTW `isContiguous` and `isMemory` should be members of `std.experimental.ndslice.slice.Slice` right, not free functions in the module? (It was not clear from your comment "module:ndslice.slice".)

## 3. Postconditions

Should I add `isContiguous`  to `makeSlice`, `slice` and `sliced` as an 1) `out` contract, 2) ddoc paragraph, or 3) both? I can also add `isMemory` to `makeSlice` and `slice`.

**Comment by PetarKirov** [comment]
I have updated my WIP [branch](https://github.com/dlang/phobos/compare/master...ZombineDev:ndslice-contiguous-layout).

**Comment by 9il** [comment]
Thanks @ZombineDev Lets move forward with variant 5.

> I prefer the isContiguous name too. But I wonder if I should refactor the is(PureRange == Range) && hasPtrBehavior!PureRange check into an enum isMemory. That way isContiguous would useable for Slices such as Iota and if the users want they can use isMemory && isContiguous to see if they can use memcpy.

No, the `isMemory` should be approved together with other templates like `isSlice`, `Vector`, `Matrix`, `isVector`, `isMatrix`. The problem that D does not allow to write code like:

``` d
alias Matrix(T) = Slice!(2, T*);
auto bar(M : Matrix!T, T)(M matrix)
{
}
```

> BTW isContiguous and isMemory should be members of std.experimental.ndslice.slice.Slice right, not free functions in the module? (It was not clear from your comment "module:ndslice.slice".)
> 
> BTW isContiguous and isMemory should be members of std.experimental.ndslice.slice.Slice right, not free functions in the module? (It was not clear from your comment "module:ndslice.slice".)

Free functions / templates looks more useful, though. In addition, they would not generate code if they are not used.

**Comment by 9il** [comment]
> Should I add isContiguous to makeSlice, slice and sliced as an 1) out contract, 2) ddoc paragraph, or 3) both?

DDOC paragraph is enought

**Comment by ljubobratovicrelja** [comment]
Ping @ZombineDev - How is it going here? Was there a phobos PR?

**Comment by 9il** [comment]
http://docs.algorithm.dlang.io/latest/mir_ndslice_slice.html#.mir_slice.field
