### ISSUE TITLE
mir.random.nonuniform

### ISSUE THREAD

**Issue by wilzbach** [9il/dip80-ndslice#262]
- [ ] Normal (#261)
- [ ] Gamma
- [ ] Generalized gamma
- [ ] Generalized inverse gaussian
- [ ] Normal inverse gaussian
- [ ] Mixtures (#233)
- [ ] Pareto, Weibull, Exponential and others.

CC @9il @joseph-wakeling-sociomantic
##

**Comment by joseph-wakeling-sociomantic** [comment]
Bikesheddy, but I would suggest `mir.random.distribution`.

The generator vs. distribution of the C++11 standard is useful -- it distinguishes between sources of uniformly-distributed random bits, vs. functions that transform random bits into variates following a particular statistical distribution:
http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2013/n3551.pdf

N.B. the standard also distinguishes between random _engines_ (pseudo-random generators) versus random _devices_ (nondeterministic generators).

Following this terminology is in line with phobos' implicit terminology and keeps a nice separation of concerns.

Note also that in this setup, `uniform` is just another distribution -- as it should be; because it's not (or shouldn't be) just a naive use of the uniform statistics of the underlying bits; there are genuine complications involved in transforming 32 or 64 random bits into a properly uniformly-distributed number across a different interval.

Uniform vs. non-uniform is a nice distinction in statistics, but it's not a meaningful distinction in API design.

**Comment by wilzbach** [comment]
> Bikesheddy, but I would suggest mir.random.distribution.
> 
> The generator vs. distribution of the C++11 standard is useful -- it distinguishes between sources of uniformly-distributed random bits, vs. functions that transform random bits into variates following a particular statistical distribution:
> ...
> Uniform vs. non-uniform is a nice distinction in statistics, but it's not a meaningful distinction in API design.

@joseph-wakeling-sociomantic convinced me that a distinction between engine and distribution is useful. That being said I think it helps in the API design if the users knows whether discrete or float (nonuniform) values are expected to be returned. That brings us to the following three possible designs?

a)

```
mir.random.discrete
mir.random.engines
mir.random.nonuniform
```

b)

```
mir.random.dists.discrete
mir.random.dists.nonuniform
mir.random.engines
```

c)

```
mir.random.dists
mir.random.engines
```

@9il what is your opinion on this matter?

**Comment by 9il** [comment]
a)

**Comment by 9il** [comment]
fixed in mir-random
