### ISSUE TITLE
link to the blog with `Flex` label

### ISSUE THREAD

**Issue by 9il** [9il/dip80-ndslice#302]
We need `Flex` label in the blog and issues. And links to the blog and github retrospectively from Flex API docs.
##

**Comment by wilzbach** [comment]
> We need Flex label in the blog and issues.

I created the "random" category for the Blog, because I assume those two posts will be the only two "Flex" posts, but I hope there will be more "random" posts and it usually gives a better impression if a category isn't entirely empty ;-)
That being said I don't mind at all about Github issue.

>  And links to the blog and github retrospectively from Flex API docs.

We officially haven't published the Blog yet, hence I didn't link to it (yet).

**Comment by 9il** [comment]
We need `Flex` labels for API docs. `random` will have a lot of tickets and posts
